### ISSUE TITLE
Proper license should be added

### ISSUE THREAD

**Issue by jjren** [shuaigroup/Renormalizer#28]
I think a proper license should be added. What do you think about it? @liwt31

**Comment by liwt31** [comment]
Some reasonable choices:
- MIT. Used in [pytenet](https://github.com/cmendl/pytenet/blob/master/LICENSE)(BSD-2 seems to be similar with MIT), [evoMPS](https://github.com/amilsted/evoMPS/blob/master/LICENSE.txt)
- Apache 2.0. Used in [pyscf](https://github.com/pyscf/pyscf/blob/master/LICENSE), [quimb](https://github.com/jcmgray/quimb/blob/develop/LICENSE.txt), [ITensor](https://github.com/ITensor/ITensor/blob/v3/LICENSE), [TensorNetwork](https://github.com/google/TensorNetwork/blob/master/LICENSE)
- GPL. Used in [tenpy](https://github.com/tenpy/tenpy/blob/master/LICENSE)

MIT is the freest license, it almost has no limitations to users. Apache is slightly more strict, requiring users to state their changes. GPL is the most strict one, requiring users to use GPL license.

I'm preferring Apache because it seems to be the most popular one.

**Comment by liwt31** [comment]
Another issue about licenses is that we need to include licenses of the third-party libs that we use, which is written in the terms of their license. I think I can figure this out when I have some time.

**Comment by jjren** [comment]
Apache 2.0 seems appropriate. 
I just opened an issue #30 to list all the 3rd-party libraries in Renormalizer.
