### ISSUE TITLE
Determine an official abbreviation for `renormalizer`

### ISSUE THREAD

**Issue by liwt31** [shuaigroup/Renormalizer#58]
In certain cases, we will have to refer to the project name. For example:
https://github.com/shuaigroup/Renormalizer/blob/267f157cff2c64a435bce755e009701c747837c7/renormalizer/mps/backend.py#L14

This is legacy code and an important reason why I haven't updated it is that renaming it to `RENORMALIZER_GPU` will make it more difficult to use in the command line.
Maybe an abbreviation for `renormalizer` can solve this. Some brainstorm results:
- renmlzer
- renmlz
- rnmlz
- reno
- ren
- renorm
- lizer

and so on...

**Comment by jjren** [comment]
I vote for "reno".  It is also the name of my conda environment. :D

**Comment by liwt31** [comment]
😆 I was thinking about *ren* actually because it's really funny (and a letter shorter than `reno`)

**Comment by jjren** [comment]
reno sounds much cute.

**Comment by liwt31** [comment]
@jiangtong1000 how about you? I'm OK with reno.

**Comment by jiangtong1000** [comment]
> @jiangtong1000 how about you? I'm OK with reno.
Sure, I'm OK, either. At first glance I thought maybe I had met `reno` before😂, which turns out to the name of one flagship phone released by oppo recently. They use `reno` as the abbreviation of `renovation`, I guess it is a self-invented word from `reformation` and `innovation`. And also, `reno` sounds like a cartoon name.

**Comment by liwt31** [comment]
Reno it is then.
